name: Create a (Pre)release on NuGet

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-preview[0-9]+"

jobs:
  release-nuget:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Verify commit exists in origin/main
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/main

      - name: Get version information from tag
        id: get_version
        run: |
          $version="${{ github.ref_name }}".TrimStart("v")
          "version-without-v=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Pack NuGet package
        run: |
          dotnet pack src/BadgeMaui/BadgeMaui.csproj `
            -c Release `
            -p:PackageVersion=${{ steps.get_version.outputs.version-without-v }}

      - name: Push NuGet package
        run: |
          $package = Get-ChildItem -Path . -Recurse -Filter *.nupkg | Select-Object -First 1
          dotnet nuget push $package.FullName `
            -s https://api.nuget.org/v3/index.json `
            -k ${{ secrets.NUGETAPIKEY }}
